version: '3'

services: 
  app:
    container_name: docker-node-backend-server
    restart: always
    build: 
      context: .
      dockerfile: ./compose/Dockerfile
    ports:
      - '80:3000'
    links:
      - mongo
    
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'